/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPlatformAdminRouteImport } from './routes/_authenticated/platform-admin'
import { Route as AuthenticatedOrgSettingsRouteImport } from './routes/_authenticated/org-settings'
import { Route as AuthenticatedWorkspaceWatchlistsRouteImport } from './routes/_authenticated/workspace.watchlists'
import { Route as AuthenticatedWorkspaceTasksRouteImport } from './routes/_authenticated/workspace.tasks'
import { Route as AuthenticatedWorkspaceSourcesRouteImport } from './routes/_authenticated/workspace.sources'
import { Route as AuthenticatedWorkspaceReportsRouteImport } from './routes/_authenticated/workspace.reports'
import { Route as AuthenticatedWorkspaceNarrativesRouteImport } from './routes/_authenticated/workspace.narratives'
import { Route as AuthenticatedWorkspaceLiveRouteImport } from './routes/_authenticated/workspace.live'
import { Route as AuthenticatedWorkspaceKnowledgeRouteImport } from './routes/_authenticated/workspace.knowledge'
import { Route as AuthenticatedWorkspaceInvestigationsRouteImport } from './routes/_authenticated/workspace.investigations'
import { Route as AuthenticatedValidationQueueRouteImport } from './routes/_authenticated/validation.queue'
import { Route as AuthenticatedValidationOutcomesRouteImport } from './routes/_authenticated/validation.outcomes'
import { Route as AuthenticatedValidationMetricsRouteImport } from './routes/_authenticated/validation.metrics'
import { Route as AuthenticatedShowcaseWalkthroughRouteImport } from './routes/_authenticated/showcase.walkthrough'
import { Route as AuthenticatedShowcasePreservationRouteImport } from './routes/_authenticated/showcase.preservation'
import { Route as AuthenticatedShowcasePortfolioRouteImport } from './routes/_authenticated/showcase.portfolio'
import { Route as AuthenticatedShowcaseCaseStudiesRouteImport } from './routes/_authenticated/showcase.case-studies'
import { Route as AuthenticatedResearchLongitudinalRouteImport } from './routes/_authenticated/research.longitudinal'
import { Route as AuthenticatedResearchExperimentsRouteImport } from './routes/_authenticated/research.experiments'
import { Route as AuthenticatedResearchEvolutionRouteImport } from './routes/_authenticated/research.evolution'
import { Route as AuthenticatedResearchDatasetsRouteImport } from './routes/_authenticated/research.datasets'
import { Route as AuthenticatedResearchBenchmarksRouteImport } from './routes/_authenticated/research.benchmarks'
import { Route as AuthenticatedOrgTeamsRouteImport } from './routes/_authenticated/org.teams'
import { Route as AuthenticatedOrgProfileRouteImport } from './routes/_authenticated/org.profile'
import { Route as AuthenticatedOperationsAuditRouteImport } from './routes/_authenticated/operations.audit'
import { Route as AuthenticatedOperationsAnalyticsRouteImport } from './routes/_authenticated/operations.analytics'
import { Route as AuthenticatedOperationsActivityRouteImport } from './routes/_authenticated/operations.activity'
import { Route as AuthenticatedDeveloperWorkflowsRouteImport } from './routes/_authenticated/developer.workflows'
import { Route as AuthenticatedDeveloperRulesRouteImport } from './routes/_authenticated/developer.rules'
import { Route as AuthenticatedDeveloperPortalRouteImport } from './routes/_authenticated/developer.portal'
import { Route as AuthenticatedDeveloperCatalogRouteImport } from './routes/_authenticated/developer.catalog'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin.system'
import { Route as AuthenticatedAdminIngestionRouteImport } from './routes/_authenticated/admin.ingestion'
import { Route as AuthenticatedWorkspaceInvestigationsIdRouteImport } from './routes/_authenticated/workspace.investigations.$id'

const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlatformAdminRoute =
  AuthenticatedPlatformAdminRouteImport.update({
    id: '/platform-admin',
    path: '/platform-admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgSettingsRoute =
  AuthenticatedOrgSettingsRouteImport.update({
    id: '/org-settings',
    path: '/org-settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceWatchlistsRoute =
  AuthenticatedWorkspaceWatchlistsRouteImport.update({
    id: '/workspace/watchlists',
    path: '/workspace/watchlists',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceTasksRoute =
  AuthenticatedWorkspaceTasksRouteImport.update({
    id: '/workspace/tasks',
    path: '/workspace/tasks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceSourcesRoute =
  AuthenticatedWorkspaceSourcesRouteImport.update({
    id: '/workspace/sources',
    path: '/workspace/sources',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceReportsRoute =
  AuthenticatedWorkspaceReportsRouteImport.update({
    id: '/workspace/reports',
    path: '/workspace/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceNarrativesRoute =
  AuthenticatedWorkspaceNarrativesRouteImport.update({
    id: '/workspace/narratives',
    path: '/workspace/narratives',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceLiveRoute =
  AuthenticatedWorkspaceLiveRouteImport.update({
    id: '/workspace/live',
    path: '/workspace/live',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceKnowledgeRoute =
  AuthenticatedWorkspaceKnowledgeRouteImport.update({
    id: '/workspace/knowledge',
    path: '/workspace/knowledge',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceInvestigationsRoute =
  AuthenticatedWorkspaceInvestigationsRouteImport.update({
    id: '/workspace/investigations',
    path: '/workspace/investigations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedValidationQueueRoute =
  AuthenticatedValidationQueueRouteImport.update({
    id: '/validation/queue',
    path: '/validation/queue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedValidationOutcomesRoute =
  AuthenticatedValidationOutcomesRouteImport.update({
    id: '/validation/outcomes',
    path: '/validation/outcomes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedValidationMetricsRoute =
  AuthenticatedValidationMetricsRouteImport.update({
    id: '/validation/metrics',
    path: '/validation/metrics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShowcaseWalkthroughRoute =
  AuthenticatedShowcaseWalkthroughRouteImport.update({
    id: '/showcase/walkthrough',
    path: '/showcase/walkthrough',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShowcasePreservationRoute =
  AuthenticatedShowcasePreservationRouteImport.update({
    id: '/showcase/preservation',
    path: '/showcase/preservation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShowcasePortfolioRoute =
  AuthenticatedShowcasePortfolioRouteImport.update({
    id: '/showcase/portfolio',
    path: '/showcase/portfolio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedShowcaseCaseStudiesRoute =
  AuthenticatedShowcaseCaseStudiesRouteImport.update({
    id: '/showcase/case-studies',
    path: '/showcase/case-studies',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchLongitudinalRoute =
  AuthenticatedResearchLongitudinalRouteImport.update({
    id: '/research/longitudinal',
    path: '/research/longitudinal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchExperimentsRoute =
  AuthenticatedResearchExperimentsRouteImport.update({
    id: '/research/experiments',
    path: '/research/experiments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchEvolutionRoute =
  AuthenticatedResearchEvolutionRouteImport.update({
    id: '/research/evolution',
    path: '/research/evolution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchDatasetsRoute =
  AuthenticatedResearchDatasetsRouteImport.update({
    id: '/research/datasets',
    path: '/research/datasets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearchBenchmarksRoute =
  AuthenticatedResearchBenchmarksRouteImport.update({
    id: '/research/benchmarks',
    path: '/research/benchmarks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgTeamsRoute = AuthenticatedOrgTeamsRouteImport.update({
  id: '/org/teams',
  path: '/org/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrgProfileRoute = AuthenticatedOrgProfileRouteImport.update({
  id: '/org/profile',
  path: '/org/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOperationsAuditRoute =
  AuthenticatedOperationsAuditRouteImport.update({
    id: '/operations/audit',
    path: '/operations/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsAnalyticsRoute =
  AuthenticatedOperationsAnalyticsRouteImport.update({
    id: '/operations/analytics',
    path: '/operations/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOperationsActivityRoute =
  AuthenticatedOperationsActivityRouteImport.update({
    id: '/operations/activity',
    path: '/operations/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperWorkflowsRoute =
  AuthenticatedDeveloperWorkflowsRouteImport.update({
    id: '/developer/workflows',
    path: '/developer/workflows',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperRulesRoute =
  AuthenticatedDeveloperRulesRouteImport.update({
    id: '/developer/rules',
    path: '/developer/rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperPortalRoute =
  AuthenticatedDeveloperPortalRouteImport.update({
    id: '/developer/portal',
    path: '/developer/portal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperCatalogRoute =
  AuthenticatedDeveloperCatalogRouteImport.update({
    id: '/developer/catalog',
    path: '/developer/catalog',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/admin/system',
    path: '/admin/system',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIngestionRoute =
  AuthenticatedAdminIngestionRouteImport.update({
    id: '/admin/ingestion',
    path: '/admin/ingestion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceInvestigationsIdRoute =
  AuthenticatedWorkspaceInvestigationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedWorkspaceInvestigationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/org-settings': typeof AuthenticatedOrgSettingsRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/developer/catalog': typeof AuthenticatedDeveloperCatalogRoute
  '/developer/portal': typeof AuthenticatedDeveloperPortalRoute
  '/developer/rules': typeof AuthenticatedDeveloperRulesRoute
  '/developer/workflows': typeof AuthenticatedDeveloperWorkflowsRoute
  '/operations/activity': typeof AuthenticatedOperationsActivityRoute
  '/operations/analytics': typeof AuthenticatedOperationsAnalyticsRoute
  '/operations/audit': typeof AuthenticatedOperationsAuditRoute
  '/org/profile': typeof AuthenticatedOrgProfileRoute
  '/org/teams': typeof AuthenticatedOrgTeamsRoute
  '/research/benchmarks': typeof AuthenticatedResearchBenchmarksRoute
  '/research/datasets': typeof AuthenticatedResearchDatasetsRoute
  '/research/evolution': typeof AuthenticatedResearchEvolutionRoute
  '/research/experiments': typeof AuthenticatedResearchExperimentsRoute
  '/research/longitudinal': typeof AuthenticatedResearchLongitudinalRoute
  '/showcase/case-studies': typeof AuthenticatedShowcaseCaseStudiesRoute
  '/showcase/portfolio': typeof AuthenticatedShowcasePortfolioRoute
  '/showcase/preservation': typeof AuthenticatedShowcasePreservationRoute
  '/showcase/walkthrough': typeof AuthenticatedShowcaseWalkthroughRoute
  '/validation/metrics': typeof AuthenticatedValidationMetricsRoute
  '/validation/outcomes': typeof AuthenticatedValidationOutcomesRoute
  '/validation/queue': typeof AuthenticatedValidationQueueRoute
  '/workspace/investigations': typeof AuthenticatedWorkspaceInvestigationsRouteWithChildren
  '/workspace/knowledge': typeof AuthenticatedWorkspaceKnowledgeRoute
  '/workspace/live': typeof AuthenticatedWorkspaceLiveRoute
  '/workspace/narratives': typeof AuthenticatedWorkspaceNarrativesRoute
  '/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/workspace/sources': typeof AuthenticatedWorkspaceSourcesRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/workspace/watchlists': typeof AuthenticatedWorkspaceWatchlistsRoute
  '/workspace/investigations/$id': typeof AuthenticatedWorkspaceInvestigationsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/org-settings': typeof AuthenticatedOrgSettingsRoute
  '/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/developer/catalog': typeof AuthenticatedDeveloperCatalogRoute
  '/developer/portal': typeof AuthenticatedDeveloperPortalRoute
  '/developer/rules': typeof AuthenticatedDeveloperRulesRoute
  '/developer/workflows': typeof AuthenticatedDeveloperWorkflowsRoute
  '/operations/activity': typeof AuthenticatedOperationsActivityRoute
  '/operations/analytics': typeof AuthenticatedOperationsAnalyticsRoute
  '/operations/audit': typeof AuthenticatedOperationsAuditRoute
  '/org/profile': typeof AuthenticatedOrgProfileRoute
  '/org/teams': typeof AuthenticatedOrgTeamsRoute
  '/research/benchmarks': typeof AuthenticatedResearchBenchmarksRoute
  '/research/datasets': typeof AuthenticatedResearchDatasetsRoute
  '/research/evolution': typeof AuthenticatedResearchEvolutionRoute
  '/research/experiments': typeof AuthenticatedResearchExperimentsRoute
  '/research/longitudinal': typeof AuthenticatedResearchLongitudinalRoute
  '/showcase/case-studies': typeof AuthenticatedShowcaseCaseStudiesRoute
  '/showcase/portfolio': typeof AuthenticatedShowcasePortfolioRoute
  '/showcase/preservation': typeof AuthenticatedShowcasePreservationRoute
  '/showcase/walkthrough': typeof AuthenticatedShowcaseWalkthroughRoute
  '/validation/metrics': typeof AuthenticatedValidationMetricsRoute
  '/validation/outcomes': typeof AuthenticatedValidationOutcomesRoute
  '/validation/queue': typeof AuthenticatedValidationQueueRoute
  '/workspace/investigations': typeof AuthenticatedWorkspaceInvestigationsRouteWithChildren
  '/workspace/knowledge': typeof AuthenticatedWorkspaceKnowledgeRoute
  '/workspace/live': typeof AuthenticatedWorkspaceLiveRoute
  '/workspace/narratives': typeof AuthenticatedWorkspaceNarrativesRoute
  '/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/workspace/sources': typeof AuthenticatedWorkspaceSourcesRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/workspace/watchlists': typeof AuthenticatedWorkspaceWatchlistsRoute
  '/workspace/investigations/$id': typeof AuthenticatedWorkspaceInvestigationsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/overview': typeof OverviewRoute
  '/_authenticated/org-settings': typeof AuthenticatedOrgSettingsRoute
  '/_authenticated/platform-admin': typeof AuthenticatedPlatformAdminRoute
  '/_authenticated/admin/ingestion': typeof AuthenticatedAdminIngestionRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/developer/catalog': typeof AuthenticatedDeveloperCatalogRoute
  '/_authenticated/developer/portal': typeof AuthenticatedDeveloperPortalRoute
  '/_authenticated/developer/rules': typeof AuthenticatedDeveloperRulesRoute
  '/_authenticated/developer/workflows': typeof AuthenticatedDeveloperWorkflowsRoute
  '/_authenticated/operations/activity': typeof AuthenticatedOperationsActivityRoute
  '/_authenticated/operations/analytics': typeof AuthenticatedOperationsAnalyticsRoute
  '/_authenticated/operations/audit': typeof AuthenticatedOperationsAuditRoute
  '/_authenticated/org/profile': typeof AuthenticatedOrgProfileRoute
  '/_authenticated/org/teams': typeof AuthenticatedOrgTeamsRoute
  '/_authenticated/research/benchmarks': typeof AuthenticatedResearchBenchmarksRoute
  '/_authenticated/research/datasets': typeof AuthenticatedResearchDatasetsRoute
  '/_authenticated/research/evolution': typeof AuthenticatedResearchEvolutionRoute
  '/_authenticated/research/experiments': typeof AuthenticatedResearchExperimentsRoute
  '/_authenticated/research/longitudinal': typeof AuthenticatedResearchLongitudinalRoute
  '/_authenticated/showcase/case-studies': typeof AuthenticatedShowcaseCaseStudiesRoute
  '/_authenticated/showcase/portfolio': typeof AuthenticatedShowcasePortfolioRoute
  '/_authenticated/showcase/preservation': typeof AuthenticatedShowcasePreservationRoute
  '/_authenticated/showcase/walkthrough': typeof AuthenticatedShowcaseWalkthroughRoute
  '/_authenticated/validation/metrics': typeof AuthenticatedValidationMetricsRoute
  '/_authenticated/validation/outcomes': typeof AuthenticatedValidationOutcomesRoute
  '/_authenticated/validation/queue': typeof AuthenticatedValidationQueueRoute
  '/_authenticated/workspace/investigations': typeof AuthenticatedWorkspaceInvestigationsRouteWithChildren
  '/_authenticated/workspace/knowledge': typeof AuthenticatedWorkspaceKnowledgeRoute
  '/_authenticated/workspace/live': typeof AuthenticatedWorkspaceLiveRoute
  '/_authenticated/workspace/narratives': typeof AuthenticatedWorkspaceNarrativesRoute
  '/_authenticated/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/_authenticated/workspace/sources': typeof AuthenticatedWorkspaceSourcesRoute
  '/_authenticated/workspace/tasks': typeof AuthenticatedWorkspaceTasksRoute
  '/_authenticated/workspace/watchlists': typeof AuthenticatedWorkspaceWatchlistsRoute
  '/_authenticated/workspace/investigations/$id': typeof AuthenticatedWorkspaceInvestigationsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/org-settings'
    | '/platform-admin'
    | '/admin/ingestion'
    | '/admin/system'
    | '/admin/users'
    | '/developer/catalog'
    | '/developer/portal'
    | '/developer/rules'
    | '/developer/workflows'
    | '/operations/activity'
    | '/operations/analytics'
    | '/operations/audit'
    | '/org/profile'
    | '/org/teams'
    | '/research/benchmarks'
    | '/research/datasets'
    | '/research/evolution'
    | '/research/experiments'
    | '/research/longitudinal'
    | '/showcase/case-studies'
    | '/showcase/portfolio'
    | '/showcase/preservation'
    | '/showcase/walkthrough'
    | '/validation/metrics'
    | '/validation/outcomes'
    | '/validation/queue'
    | '/workspace/investigations'
    | '/workspace/knowledge'
    | '/workspace/live'
    | '/workspace/narratives'
    | '/workspace/reports'
    | '/workspace/sources'
    | '/workspace/tasks'
    | '/workspace/watchlists'
    | '/workspace/investigations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/org-settings'
    | '/platform-admin'
    | '/admin/ingestion'
    | '/admin/system'
    | '/admin/users'
    | '/developer/catalog'
    | '/developer/portal'
    | '/developer/rules'
    | '/developer/workflows'
    | '/operations/activity'
    | '/operations/analytics'
    | '/operations/audit'
    | '/org/profile'
    | '/org/teams'
    | '/research/benchmarks'
    | '/research/datasets'
    | '/research/evolution'
    | '/research/experiments'
    | '/research/longitudinal'
    | '/showcase/case-studies'
    | '/showcase/portfolio'
    | '/showcase/preservation'
    | '/showcase/walkthrough'
    | '/validation/metrics'
    | '/validation/outcomes'
    | '/validation/queue'
    | '/workspace/investigations'
    | '/workspace/knowledge'
    | '/workspace/live'
    | '/workspace/narratives'
    | '/workspace/reports'
    | '/workspace/sources'
    | '/workspace/tasks'
    | '/workspace/watchlists'
    | '/workspace/investigations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/overview'
    | '/_authenticated/org-settings'
    | '/_authenticated/platform-admin'
    | '/_authenticated/admin/ingestion'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/users'
    | '/_authenticated/developer/catalog'
    | '/_authenticated/developer/portal'
    | '/_authenticated/developer/rules'
    | '/_authenticated/developer/workflows'
    | '/_authenticated/operations/activity'
    | '/_authenticated/operations/analytics'
    | '/_authenticated/operations/audit'
    | '/_authenticated/org/profile'
    | '/_authenticated/org/teams'
    | '/_authenticated/research/benchmarks'
    | '/_authenticated/research/datasets'
    | '/_authenticated/research/evolution'
    | '/_authenticated/research/experiments'
    | '/_authenticated/research/longitudinal'
    | '/_authenticated/showcase/case-studies'
    | '/_authenticated/showcase/portfolio'
    | '/_authenticated/showcase/preservation'
    | '/_authenticated/showcase/walkthrough'
    | '/_authenticated/validation/metrics'
    | '/_authenticated/validation/outcomes'
    | '/_authenticated/validation/queue'
    | '/_authenticated/workspace/investigations'
    | '/_authenticated/workspace/knowledge'
    | '/_authenticated/workspace/live'
    | '/_authenticated/workspace/narratives'
    | '/_authenticated/workspace/reports'
    | '/_authenticated/workspace/sources'
    | '/_authenticated/workspace/tasks'
    | '/_authenticated/workspace/watchlists'
    | '/_authenticated/workspace/investigations/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OverviewRoute: typeof OverviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/platform-admin': {
      id: '/_authenticated/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof AuthenticatedPlatformAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org-settings': {
      id: '/_authenticated/org-settings'
      path: '/org-settings'
      fullPath: '/org-settings'
      preLoaderRoute: typeof AuthenticatedOrgSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/watchlists': {
      id: '/_authenticated/workspace/watchlists'
      path: '/workspace/watchlists'
      fullPath: '/workspace/watchlists'
      preLoaderRoute: typeof AuthenticatedWorkspaceWatchlistsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/tasks': {
      id: '/_authenticated/workspace/tasks'
      path: '/workspace/tasks'
      fullPath: '/workspace/tasks'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/sources': {
      id: '/_authenticated/workspace/sources'
      path: '/workspace/sources'
      fullPath: '/workspace/sources'
      preLoaderRoute: typeof AuthenticatedWorkspaceSourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/reports': {
      id: '/_authenticated/workspace/reports'
      path: '/workspace/reports'
      fullPath: '/workspace/reports'
      preLoaderRoute: typeof AuthenticatedWorkspaceReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/narratives': {
      id: '/_authenticated/workspace/narratives'
      path: '/workspace/narratives'
      fullPath: '/workspace/narratives'
      preLoaderRoute: typeof AuthenticatedWorkspaceNarrativesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/live': {
      id: '/_authenticated/workspace/live'
      path: '/workspace/live'
      fullPath: '/workspace/live'
      preLoaderRoute: typeof AuthenticatedWorkspaceLiveRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/knowledge': {
      id: '/_authenticated/workspace/knowledge'
      path: '/workspace/knowledge'
      fullPath: '/workspace/knowledge'
      preLoaderRoute: typeof AuthenticatedWorkspaceKnowledgeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/investigations': {
      id: '/_authenticated/workspace/investigations'
      path: '/workspace/investigations'
      fullPath: '/workspace/investigations'
      preLoaderRoute: typeof AuthenticatedWorkspaceInvestigationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validation/queue': {
      id: '/_authenticated/validation/queue'
      path: '/validation/queue'
      fullPath: '/validation/queue'
      preLoaderRoute: typeof AuthenticatedValidationQueueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validation/outcomes': {
      id: '/_authenticated/validation/outcomes'
      path: '/validation/outcomes'
      fullPath: '/validation/outcomes'
      preLoaderRoute: typeof AuthenticatedValidationOutcomesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/validation/metrics': {
      id: '/_authenticated/validation/metrics'
      path: '/validation/metrics'
      fullPath: '/validation/metrics'
      preLoaderRoute: typeof AuthenticatedValidationMetricsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/walkthrough': {
      id: '/_authenticated/showcase/walkthrough'
      path: '/showcase/walkthrough'
      fullPath: '/showcase/walkthrough'
      preLoaderRoute: typeof AuthenticatedShowcaseWalkthroughRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/preservation': {
      id: '/_authenticated/showcase/preservation'
      path: '/showcase/preservation'
      fullPath: '/showcase/preservation'
      preLoaderRoute: typeof AuthenticatedShowcasePreservationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/portfolio': {
      id: '/_authenticated/showcase/portfolio'
      path: '/showcase/portfolio'
      fullPath: '/showcase/portfolio'
      preLoaderRoute: typeof AuthenticatedShowcasePortfolioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/showcase/case-studies': {
      id: '/_authenticated/showcase/case-studies'
      path: '/showcase/case-studies'
      fullPath: '/showcase/case-studies'
      preLoaderRoute: typeof AuthenticatedShowcaseCaseStudiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/longitudinal': {
      id: '/_authenticated/research/longitudinal'
      path: '/research/longitudinal'
      fullPath: '/research/longitudinal'
      preLoaderRoute: typeof AuthenticatedResearchLongitudinalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/experiments': {
      id: '/_authenticated/research/experiments'
      path: '/research/experiments'
      fullPath: '/research/experiments'
      preLoaderRoute: typeof AuthenticatedResearchExperimentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/evolution': {
      id: '/_authenticated/research/evolution'
      path: '/research/evolution'
      fullPath: '/research/evolution'
      preLoaderRoute: typeof AuthenticatedResearchEvolutionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/datasets': {
      id: '/_authenticated/research/datasets'
      path: '/research/datasets'
      fullPath: '/research/datasets'
      preLoaderRoute: typeof AuthenticatedResearchDatasetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/research/benchmarks': {
      id: '/_authenticated/research/benchmarks'
      path: '/research/benchmarks'
      fullPath: '/research/benchmarks'
      preLoaderRoute: typeof AuthenticatedResearchBenchmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/teams': {
      id: '/_authenticated/org/teams'
      path: '/org/teams'
      fullPath: '/org/teams'
      preLoaderRoute: typeof AuthenticatedOrgTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/org/profile': {
      id: '/_authenticated/org/profile'
      path: '/org/profile'
      fullPath: '/org/profile'
      preLoaderRoute: typeof AuthenticatedOrgProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/audit': {
      id: '/_authenticated/operations/audit'
      path: '/operations/audit'
      fullPath: '/operations/audit'
      preLoaderRoute: typeof AuthenticatedOperationsAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/analytics': {
      id: '/_authenticated/operations/analytics'
      path: '/operations/analytics'
      fullPath: '/operations/analytics'
      preLoaderRoute: typeof AuthenticatedOperationsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/operations/activity': {
      id: '/_authenticated/operations/activity'
      path: '/operations/activity'
      fullPath: '/operations/activity'
      preLoaderRoute: typeof AuthenticatedOperationsActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/workflows': {
      id: '/_authenticated/developer/workflows'
      path: '/developer/workflows'
      fullPath: '/developer/workflows'
      preLoaderRoute: typeof AuthenticatedDeveloperWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/rules': {
      id: '/_authenticated/developer/rules'
      path: '/developer/rules'
      fullPath: '/developer/rules'
      preLoaderRoute: typeof AuthenticatedDeveloperRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/portal': {
      id: '/_authenticated/developer/portal'
      path: '/developer/portal'
      fullPath: '/developer/portal'
      preLoaderRoute: typeof AuthenticatedDeveloperPortalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/catalog': {
      id: '/_authenticated/developer/catalog'
      path: '/developer/catalog'
      fullPath: '/developer/catalog'
      preLoaderRoute: typeof AuthenticatedDeveloperCatalogRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ingestion': {
      id: '/_authenticated/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AuthenticatedAdminIngestionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/investigations/$id': {
      id: '/_authenticated/workspace/investigations/$id'
      path: '/$id'
      fullPath: '/workspace/investigations/$id'
      preLoaderRoute: typeof AuthenticatedWorkspaceInvestigationsIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceInvestigationsRoute
    }
  }
}

interface AuthenticatedWorkspaceInvestigationsRouteChildren {
  AuthenticatedWorkspaceInvestigationsIdRoute: typeof AuthenticatedWorkspaceInvestigationsIdRoute
}

const AuthenticatedWorkspaceInvestigationsRouteChildren: AuthenticatedWorkspaceInvestigationsRouteChildren =
  {
    AuthenticatedWorkspaceInvestigationsIdRoute:
      AuthenticatedWorkspaceInvestigationsIdRoute,
  }

const AuthenticatedWorkspaceInvestigationsRouteWithChildren =
  AuthenticatedWorkspaceInvestigationsRoute._addFileChildren(
    AuthenticatedWorkspaceInvestigationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSettingsRoute: typeof AuthenticatedOrgSettingsRoute
  AuthenticatedPlatformAdminRoute: typeof AuthenticatedPlatformAdminRoute
  AuthenticatedAdminIngestionRoute: typeof AuthenticatedAdminIngestionRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedDeveloperCatalogRoute: typeof AuthenticatedDeveloperCatalogRoute
  AuthenticatedDeveloperPortalRoute: typeof AuthenticatedDeveloperPortalRoute
  AuthenticatedDeveloperRulesRoute: typeof AuthenticatedDeveloperRulesRoute
  AuthenticatedDeveloperWorkflowsRoute: typeof AuthenticatedDeveloperWorkflowsRoute
  AuthenticatedOperationsActivityRoute: typeof AuthenticatedOperationsActivityRoute
  AuthenticatedOperationsAnalyticsRoute: typeof AuthenticatedOperationsAnalyticsRoute
  AuthenticatedOperationsAuditRoute: typeof AuthenticatedOperationsAuditRoute
  AuthenticatedOrgProfileRoute: typeof AuthenticatedOrgProfileRoute
  AuthenticatedOrgTeamsRoute: typeof AuthenticatedOrgTeamsRoute
  AuthenticatedResearchBenchmarksRoute: typeof AuthenticatedResearchBenchmarksRoute
  AuthenticatedResearchDatasetsRoute: typeof AuthenticatedResearchDatasetsRoute
  AuthenticatedResearchEvolutionRoute: typeof AuthenticatedResearchEvolutionRoute
  AuthenticatedResearchExperimentsRoute: typeof AuthenticatedResearchExperimentsRoute
  AuthenticatedResearchLongitudinalRoute: typeof AuthenticatedResearchLongitudinalRoute
  AuthenticatedShowcaseCaseStudiesRoute: typeof AuthenticatedShowcaseCaseStudiesRoute
  AuthenticatedShowcasePortfolioRoute: typeof AuthenticatedShowcasePortfolioRoute
  AuthenticatedShowcasePreservationRoute: typeof AuthenticatedShowcasePreservationRoute
  AuthenticatedShowcaseWalkthroughRoute: typeof AuthenticatedShowcaseWalkthroughRoute
  AuthenticatedValidationMetricsRoute: typeof AuthenticatedValidationMetricsRoute
  AuthenticatedValidationOutcomesRoute: typeof AuthenticatedValidationOutcomesRoute
  AuthenticatedValidationQueueRoute: typeof AuthenticatedValidationQueueRoute
  AuthenticatedWorkspaceInvestigationsRoute: typeof AuthenticatedWorkspaceInvestigationsRouteWithChildren
  AuthenticatedWorkspaceKnowledgeRoute: typeof AuthenticatedWorkspaceKnowledgeRoute
  AuthenticatedWorkspaceLiveRoute: typeof AuthenticatedWorkspaceLiveRoute
  AuthenticatedWorkspaceNarrativesRoute: typeof AuthenticatedWorkspaceNarrativesRoute
  AuthenticatedWorkspaceReportsRoute: typeof AuthenticatedWorkspaceReportsRoute
  AuthenticatedWorkspaceSourcesRoute: typeof AuthenticatedWorkspaceSourcesRoute
  AuthenticatedWorkspaceTasksRoute: typeof AuthenticatedWorkspaceTasksRoute
  AuthenticatedWorkspaceWatchlistsRoute: typeof AuthenticatedWorkspaceWatchlistsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSettingsRoute: AuthenticatedOrgSettingsRoute,
  AuthenticatedPlatformAdminRoute: AuthenticatedPlatformAdminRoute,
  AuthenticatedAdminIngestionRoute: AuthenticatedAdminIngestionRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedDeveloperCatalogRoute: AuthenticatedDeveloperCatalogRoute,
  AuthenticatedDeveloperPortalRoute: AuthenticatedDeveloperPortalRoute,
  AuthenticatedDeveloperRulesRoute: AuthenticatedDeveloperRulesRoute,
  AuthenticatedDeveloperWorkflowsRoute: AuthenticatedDeveloperWorkflowsRoute,
  AuthenticatedOperationsActivityRoute: AuthenticatedOperationsActivityRoute,
  AuthenticatedOperationsAnalyticsRoute: AuthenticatedOperationsAnalyticsRoute,
  AuthenticatedOperationsAuditRoute: AuthenticatedOperationsAuditRoute,
  AuthenticatedOrgProfileRoute: AuthenticatedOrgProfileRoute,
  AuthenticatedOrgTeamsRoute: AuthenticatedOrgTeamsRoute,
  AuthenticatedResearchBenchmarksRoute: AuthenticatedResearchBenchmarksRoute,
  AuthenticatedResearchDatasetsRoute: AuthenticatedResearchDatasetsRoute,
  AuthenticatedResearchEvolutionRoute: AuthenticatedResearchEvolutionRoute,
  AuthenticatedResearchExperimentsRoute: AuthenticatedResearchExperimentsRoute,
  AuthenticatedResearchLongitudinalRoute:
    AuthenticatedResearchLongitudinalRoute,
  AuthenticatedShowcaseCaseStudiesRoute: AuthenticatedShowcaseCaseStudiesRoute,
  AuthenticatedShowcasePortfolioRoute: AuthenticatedShowcasePortfolioRoute,
  AuthenticatedShowcasePreservationRoute:
    AuthenticatedShowcasePreservationRoute,
  AuthenticatedShowcaseWalkthroughRoute: AuthenticatedShowcaseWalkthroughRoute,
  AuthenticatedValidationMetricsRoute: AuthenticatedValidationMetricsRoute,
  AuthenticatedValidationOutcomesRoute: AuthenticatedValidationOutcomesRoute,
  AuthenticatedValidationQueueRoute: AuthenticatedValidationQueueRoute,
  AuthenticatedWorkspaceInvestigationsRoute:
    AuthenticatedWorkspaceInvestigationsRouteWithChildren,
  AuthenticatedWorkspaceKnowledgeRoute: AuthenticatedWorkspaceKnowledgeRoute,
  AuthenticatedWorkspaceLiveRoute: AuthenticatedWorkspaceLiveRoute,
  AuthenticatedWorkspaceNarrativesRoute: AuthenticatedWorkspaceNarrativesRoute,
  AuthenticatedWorkspaceReportsRoute: AuthenticatedWorkspaceReportsRoute,
  AuthenticatedWorkspaceSourcesRoute: AuthenticatedWorkspaceSourcesRoute,
  AuthenticatedWorkspaceTasksRoute: AuthenticatedWorkspaceTasksRoute,
  AuthenticatedWorkspaceWatchlistsRoute: AuthenticatedWorkspaceWatchlistsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OverviewRoute: OverviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
